services:
  mysql:
    image: mysql:9.1.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: plantstore
      MYSQL_PASSWORD: plantstore
    ports:
      - "3306:3306"
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - './InitDb:/docker-entrypoint-initdb.d'
    restart: always

volumes:
  mysql_data: